export const services = [
  {
    slug: "software-development",
    title: "Software Development",
    short: "Web, mobile, cloud and programming solutions built around the way your team and customers work.",
    promise: "Turn a defined opportunity into reliable software people can use with confidence.",
    description: "We design and engineer focused digital products - from internal platforms to customer-facing applications - with usability, security and maintainability considered from the start.",
    capabilities: ["Web and mobile application engineering", "Cloud architecture and API integration", "Programming and system modernization", "Quality assurance and release support"],
    process: ["Understand the workflow and success criteria", "Prototype the critical experience", "Build in measurable releases", "Launch, learn and improve"],
    outputs: ["Product roadmap", "Experience prototype", "Production-ready application", "Technical documentation"],
    fit: "New digital products, modernization initiatives and operational tools that have outgrown spreadsheets or disconnected systems.",
    offerings: [
      { title: "Custom web applications", detail: "Dashboards, portals and internal platforms built with modern React front-ends and secure, well-structured back-ends." },
      { title: "Mobile applications", detail: "Cross-platform apps with offline-friendly behaviour, notifications and clean, accessible interfaces." },
      { title: "APIs and integrations", detail: "Connecting payments, messaging, ERP or existing databases so data moves without manual re-entry." },
      { title: "Cloud setup and deployment", detail: "Hosting, environments, backups and monitoring so releases are predictable rather than risky." },
      { title: "Maintenance and improvement", detail: "Ongoing fixes, performance work and feature releases after launch." },
    ],
    tech: ["React", "TypeScript", "Node.js", "Python", "PostgreSQL", "REST & GraphQL APIs", "Cloud hosting", "CI/CD"],
    faqs: [
      { q: "How long does a typical project take?", a: "A focused first release usually takes a few weeks to a few months, depending on scope. We plan it in stages so you see working software early." },
      { q: "Can you work with our existing system?", a: "Yes. We regularly extend or integrate with existing databases, tools and third-party services rather than replacing everything." },
      { q: "Who owns the code?", a: "You do. Source code, documentation and accounts are handed over to you." },
    ],
  },
  {
    slug: "ai-machine-learning",
    title: "AI & Machine Learning",
    short: "AI, machine learning, deep learning, GenAI, computer vision and NLP for practical outcomes.",
    promise: "Move from an AI idea to a controlled, measurable system with a clear business purpose.",
    description: "We identify where AI can create genuine value, validate the data and workflow, then build solutions with human oversight, evaluation and responsible deployment in mind.",
    capabilities: ["AI, ML and deep learning systems", "Generative AI and knowledge assistants", "Computer vision and natural language processing", "Model evaluation and integration"],
    process: ["Define the decision or task to improve", "Assess available data and risk", "Prototype and evaluate", "Integrate with clear safeguards"],
    outputs: ["Feasibility report", "Working proof of concept", "Evaluation framework", "Integrated AI capability"],
    fit: "Teams with a repeatable decision, information bottleneck or manual process that can be measured before and after implementation.",
    offerings: [
      { title: "Prediction and forecasting models", detail: "Demand, failure, risk or quality predictions built on your historical data and validated against real outcomes." },
      { title: "Computer vision", detail: "Image and video models for inspection, counting, detection and quality checks." },
      { title: "Document and knowledge assistants", detail: "Question-answering over your own manuals, reports and records, with source references." },
      { title: "Workflow automation with AI", detail: "Classifying, summarising and routing incoming information so people spend time on judgement, not sorting." },
      { title: "Model evaluation and monitoring", detail: "Accuracy tracking, drift checks and human review steps so behaviour stays understood over time." },
    ],
    tech: ["Python", "PyTorch", "scikit-learn", "OpenCV", "LLM APIs", "Vector databases", "MLOps pipelines"],
    faqs: [
      { q: "We do not have much data. Can we still start?", a: "Often yes. We begin with a readiness check and, where data is thin, start with rule-based or pre-trained approaches while data is collected properly." },
      { q: "How do you keep AI outputs trustworthy?", a: "Every build includes an evaluation set, clear limits on what the system decides alone, and a human review step for high-impact cases." },
      { q: "Will our data be used to train public models?", a: "No. Data handling is agreed in writing before work starts." },
    ],
  },
  {
    slug: "iot-solutions",
    title: "IoT & Smart Systems",
    short: "IoT, sensors, Arduino and Raspberry Pi systems that make physical operations visible and actionable.",
    promise: "Connect field conditions to the people who need to understand and act on them.",
    description: "We bring sensors, gateways, connectivity and software together as one dependable system, designed for the realities of installation, maintenance and daily use.",
    capabilities: ["IoT and sensor architecture", "Arduino and Raspberry Pi prototyping", "Device connectivity and data pipelines", "Monitoring, alerts and smart automation"],
    process: ["Map the environment and decisions", "Select and test the sensing approach", "Pilot in real conditions", "Scale with monitoring and support"],
    outputs: ["System architecture", "Connected prototype", "Operations dashboard", "Deployment playbook"],
    fit: "Agriculture, facilities, energy and distributed operations where teams need timely insight beyond manual checks.",
    offerings: [
      { title: "Sensor node design", detail: "Selecting and assembling sensing hardware for temperature, moisture, power, motion, air quality and more." },
      { title: "Connectivity and gateways", detail: "WiFi, LoRa, GSM or BLE links chosen for range, power and site conditions, with reliable buffering when networks drop." },
      { title: "Monitoring dashboards", detail: "Live readings, history, thresholds and exports that field and management teams can both use." },
      { title: "Alerts and automation", detail: "SMS, email or app notifications triggered by conditions, plus automatic control actions where appropriate." },
      { title: "Pilot deployment and support", detail: "Installation guidance, calibration and a maintenance plan for the first live site." },
    ],
    tech: ["ESP32", "Raspberry Pi", "LoRaWAN", "MQTT", "Node.js", "Time-series databases", "Cloud dashboards"],
    faqs: [
      { q: "Can you work at one site before scaling?", a: "Yes, and we recommend it. A pilot site proves the sensing approach and cost per node before wider rollout." },
      { q: "What if internet coverage is poor?", a: "Devices store readings locally and sync when the connection returns, so no data is lost." },
      { q: "Do you supply the hardware?", a: "We can specify it for you to procure, or assemble prototype units ourselves - whichever suits your procurement process." },
    ],
  },
  {
    slug: "robotics",
    title: "Robotics & Automation",
    short: "Robotics, automation and control systems designed for precision, repeatability and safer work.",
    promise: "Prove the right automation concept before committing to a complex deployment.",
    description: "We combine mechanical thinking, controls and software to develop task-specific robotic concepts and prototypes grounded in the operating environment.",
    capabilities: ["Robotics and automation assessment", "Motion, control and actuator prototyping", "Machine vision integration", "Safety and validation planning"],
    process: ["Observe the task and constraints", "Model the automation concept", "Build and test a prototype", "Validate performance and next steps"],
    outputs: ["Automation concept", "Functional prototype", "Test findings", "Scale-up recommendations"],
    fit: "Repetitive, hazardous or precision-critical tasks where a controlled prototype can reduce implementation risk.",
    offerings: [
      { title: "Automation feasibility study", detail: "An honest read on whether a task should be automated, partially assisted, or left to people." },
      { title: "Motion and control prototypes", detail: "Motors, drives, actuators and controllers assembled into a working rig that performs the real task." },
      { title: "Machine vision guidance", detail: "Cameras and detection models that let a system locate, sort or inspect parts." },
      { title: "Mobile and educational robots", detail: "Line-following, navigation and manipulator platforms for research, labs and demonstrations." },
      { title: "Safety and validation planning", detail: "Guarding, stop behaviour and repeatability testing documented before anything goes near production." },
    ],
    tech: ["ROS", "Arduino & STM32", "Python", "OpenCV", "3D printing", "CAD", "PLC & motor control"],
    faqs: [
      { q: "Do you build full production lines?", a: "Our strength is the concept and prototype stage. We validate the approach and hand over findings for integration partners to scale." },
      { q: "Can students or research teams work with you?", a: "Yes. We support academic robotics projects, lab setups and competition builds." },
      { q: "How is safety handled?", a: "Safe stop behaviour, guarding and operating limits are designed in from the first prototype, not added afterwards." },
    ],
  },
  {
    slug: "embedded-systems",
    title: "Embedded Systems & VLSI",
    short: "Embedded, FPGA, PCB and VLSI development for products that work beyond the lab.",
    promise: "Build the dependable intelligence inside a connected product or machine.",
    description: "We develop embedded software and integrate electronics with careful attention to power, connectivity, resilience and the conditions the device must survive.",
    capabilities: ["Firmware and embedded architecture", "FPGA and digital logic development", "Circuit and PCB design support", "VLSI design and verification foundations"],
    process: ["Define operating requirements", "Select the platform and architecture", "Develop through hardware-in-loop tests", "Validate and document"],
    outputs: ["Firmware codebase", "Integrated device prototype", "Validation results", "Manufacturing handoff package"],
    fit: "Connected products, instrumentation and control devices that require dependable behavior under real operating constraints.",
    offerings: [
      { title: "Firmware development", detail: "Bare-metal or RTOS firmware written for clarity, low power and predictable behaviour." },
      { title: "Board bring-up and peripherals", detail: "Getting sensors, displays, storage and radios talking over I2C, SPI, UART and CAN." },
      { title: "Circuit and PCB support", detail: "Schematic review, prototype wiring and guidance on layout for production boards." },
      { title: "Power optimisation", detail: "Sleep strategies and measurement so battery devices last as long as the use case demands." },
      { title: "Testing and handover", detail: "Diagnostics, firmware update paths and documentation ready for manufacturing." },
    ],
    tech: ["C / C++", "STM32", "ESP32", "FreeRTOS", "I2C / SPI / UART / CAN", "KiCad", "Oscilloscope & logic analysis"],
    faqs: [
      { q: "Can you take over firmware someone else started?", a: "Yes. We begin with a short code and hardware review so expectations on effort are clear before we continue." },
      { q: "Do you handle certification?", a: "We prepare designs and documentation with compliance in mind and work alongside your certification lab." },
      { q: "What do we receive at the end?", a: "Source firmware, build instructions, test results and a handover document for your manufacturing partner." },
    ],
  },
  {
    slug: "training-workshops",
    title: "Training & Institutional Programs",
    short: "Projects, workshops, FDP, CRT and CDC programs built around practical technology learning.",
    promise: "Give your team practical confidence, not just a presentation deck.",
    description: "We shape workshops around your participants, context and desired outcome, combining clear foundations with guided exercises and applied problem-solving.",
    capabilities: ["Student projects and technical workshops", "Faculty Development Programs (FDP)", "Campus Recruitment Training (CRT)", "Career Development Cell (CDC) programs"],
    process: ["Assess participants and goals", "Design the learning journey", "Deliver practical sessions", "Provide resources and next steps"],
    outputs: ["Tailored curriculum", "Facilitated sessions", "Hands-on exercises", "Learning resources"],
    fit: "Leadership teams, engineers, educators and organizations preparing to adopt or evaluate new technology responsibly.",
    offerings: [
      { title: "AI and machine learning foundations", detail: "What the technology can and cannot do, with guided exercises on real datasets." },
      { title: "IoT and embedded labs", detail: "Participants wire sensors, flash firmware and see their own data appear on a dashboard." },
      { title: "Robotics and automation sessions", detail: "Build, program and test a working robot task in a guided lab format." },
      { title: "Faculty and institutional programs", detail: "Curriculum support, lab setup guidance and train-the-trainer sessions for colleges." },
      { title: "Team upskilling for organisations", detail: "Custom tracks for engineering or leadership teams, built around your own use cases." },
    ],
    tech: ["On-site or online delivery", "Starter kits and lab guides", "FDP", "CRT", "CDC", "Project-based assessment"],
    faqs: [
      { q: "What group sizes do you handle?", a: "From small team sessions to full classroom cohorts. Hands-on labs work best in smaller groups with shared kits." },
      { q: "Do participants need prior experience?", a: "No. We set the starting level after a short assessment of the group." },
      { q: "Can sessions run online?", a: "Yes, with simulation and remote labs, though hardware sessions are far stronger in person." },
    ],
  },
  {
    slug: "mechanical-engineering-cad-cae",
    title: "Mechanical Engineering & CAD/CAE",
    short: "Product design, 3D modelling and engineering analysis using SolidWorks, CATIA, ANSYS and CAD workflows.",
    promise: "Move from a mechanical idea to a manufacturable, analysed and clearly documented design.",
    description: "We support mechanical product development from concept modelling and assemblies through simulation, drawings and design refinement, with deliverables structured for academic, prototype and industry use.",
    capabilities: ["3D part and assembly modelling", "CAD drafting and manufacturing drawings", "Structural and thermal CAE analysis", "Design optimization and documentation"],
    process: ["Define loads, interfaces and constraints", "Develop the CAD model", "Simulate and review performance", "Refine and prepare documentation"],
    outputs: ["3D CAD models", "Engineering drawings", "Simulation report", "Design handoff package"],
    fit: "Product developers, manufacturers, students and research teams that need a mechanical concept modelled, analysed or prepared for prototyping.",
    offerings: [
      { title: "3D modelling and assemblies", detail: "Parametric parts, mechanisms and complete assemblies developed with clear design intent." },
      { title: "CAD and production drawings", detail: "Dimensioned drawings, tolerances, exploded views and bills of materials for fabrication." },
      { title: "Structural and thermal analysis", detail: "ANSYS-based studies that examine stress, deformation, temperature and expected operating conditions." },
      { title: "Design optimization", detail: "Iterative geometry and material changes guided by manufacturability, weight and performance." },
      { title: "Prototype preparation", detail: "Models and files prepared for 3D printing, machining or fabrication partner review." },
    ],
    tech: ["SolidWorks", "CATIA", "ANSYS", "AutoCAD", "CAD", "CAE", "3D printing"],
    faqs: [
      { q: "Can you work from a sketch or existing part?", a: "Yes. We can begin from sketches, measurements, photographs or an existing CAD file after reviewing the required accuracy." },
      { q: "Do you provide simulation reports?", a: "Yes. Reports state assumptions, boundary conditions, results and practical design recommendations." },
      { q: "Can files be prepared for manufacturing?", a: "Yes. We provide suitable model formats and drawings for discussion with your chosen fabricator or manufacturer." },
    ],
  },
  {
    slug: "matlab-engineering-simulation",
    title: "MATLAB & Engineering Simulation",
    short: "MATLAB, Simulink and modelling support for analysing, testing and communicating engineering systems.",
    promise: "Turn engineering equations and system behaviour into simulations you can inspect and validate.",
    description: "We develop mathematical models, simulations and analysis workflows for control, signal, electrical and multidisciplinary engineering problems, with readable code and documented assumptions.",
    capabilities: ["MATLAB programming and data analysis", "Simulink system modelling", "Control and signal simulation", "Results visualization and validation"],
    process: ["Define the system and assumptions", "Build the mathematical model", "Simulate operating scenarios", "Validate and document findings"],
    outputs: ["MATLAB code", "Simulink model", "Plots and analysis", "Simulation report"],
    fit: "Engineering teams, researchers and students who need to model a system, test an algorithm or interpret experimental data before physical implementation.",
    offerings: [
      { title: "MATLAB programming", detail: "Structured scripts and functions for calculation, analysis, optimization and visualization." },
      { title: "Simulink modelling", detail: "Block-based dynamic models for controls, motors, power systems and connected subsystems." },
      { title: "Control-system analysis", detail: "Plant models, controller design and response evaluation across realistic operating cases." },
      { title: "Signal and data analysis", detail: "Filtering, feature extraction, plotting and statistical interpretation of measured data." },
      { title: "Model documentation", detail: "Clear assumptions, parameters, validation notes and instructions for continuing the work." },
    ],
    tech: ["MATLAB", "Simulink", "Stateflow", "Control System Toolbox", "Signal Processing", "Modelling"],
    faqs: [
      { q: "Can you improve an existing MATLAB model?", a: "Yes. We review the current code or model, identify gaps and agree the required corrections or extensions." },
      { q: "Can simulation connect to hardware work?", a: "Yes. Models can support controller design, hardware-in-loop preparation and later embedded implementation." },
      { q: "Will the model be explained?", a: "Yes. Handover includes readable files and an explanation of assumptions, parameters and results." },
    ],
  },
  {
    slug: "civil-engineering-design",
    title: "Civil Engineering & Design",
    short: "AutoCAD, Civil 3D and structural design support for clear, coordinated engineering documentation.",
    promise: "Develop civil design concepts into coordinated drawings, models and engineering documentation.",
    description: "We support civil and structural design work with drafting, site and infrastructure models, basic analysis coordination and presentation-ready technical documentation.",
    capabilities: ["2D civil and structural drafting", "Civil 3D site and infrastructure modelling", "Structural design documentation", "Quantity and drawing coordination"],
    process: ["Review the brief and available survey data", "Develop the design and drawing set", "Coordinate dimensions and requirements", "Issue reviewed documentation"],
    outputs: ["CAD drawing set", "Civil 3D model", "Design calculations", "Quantity and documentation schedule"],
    fit: "Students, consultants, contractors and project teams needing accurate civil drawings, site models or structured design support.",
    offerings: [
      { title: "AutoCAD drafting", detail: "Plans, elevations, sections and detail drawings organised to professional layer and annotation standards." },
      { title: "Civil 3D modelling", detail: "Surfaces, alignments, profiles, grading and infrastructure layouts developed from available project data." },
      { title: "Structural design support", detail: "Member layouts, basic calculations and coordinated structural documentation for review by the responsible engineer." },
      { title: "Quantity documentation", detail: "Drawing-based schedules and quantity take-offs prepared with transparent assumptions." },
      { title: "Academic and project guidance", detail: "Guided civil design projects that connect calculation, drafting and final presentation." },
    ],
    tech: ["AutoCAD", "Civil 3D", "Structural design", "Quantity take-off", "CAD standards"],
    faqs: [
      { q: "Can you work with survey or existing drawing files?", a: "Yes. We first review file quality, units and coordinate information before beginning design work." },
      { q: "Do you provide signed statutory approvals?", a: "No. Where statutory certification is required, the final design must be reviewed and signed by the appropriately licensed professional." },
      { q: "Can you support student civil projects?", a: "Yes. We provide ethical guidance, modelling and documentation support while keeping the student's authorship clear." },
    ],
  },
  {
    slug: "research-publications",
    title: "Research & Publications",
    short: "Guided research support that turns ideas into structured, publishable work.",
    promise: "Help researchers and teams move from an idea to a credible, well-presented contribution.",
    description: "We support academic and applied research journeys - from topic selection and literature review to methodology, documentation and publication readiness - with a focus on clarity, rigour and practical relevance.",
    capabilities: ["Research topic and gap identification", "Literature review and synthesis", "Methodology and experiment design", "Paper writing and journal alignment"],
    process: ["Understand the research objective", "Map the existing landscape", "Develop the approach and draft", "Refine and prepare for submission"],
    outputs: ["Research proposal", "Review document", "Draft manuscript", "Submission-ready paper"],
    fit: "Students, researchers, educators and organisations turning technical work into published, peer-reviewed or institutional research output.",
    offerings: [
      { title: "Topic and gap identification", detail: "Finding a question that is genuinely open, feasible with your resources and worth publishing." },
      { title: "Literature review", detail: "Structured reading, comparison tables and a synthesis that positions your contribution clearly." },
      { title: "Methodology and experiments", detail: "Designing the study, setting up implementation and analysing results honestly." },
      { title: "Manuscript preparation", detail: "Drafting, figures, formatting and language work aligned to the target journal or conference template." },
      { title: "Submission and revision support", detail: "Journal shortlisting, submission guidance and help responding to reviewer comments." },
    ],
    tech: ["IEEE & Springer formats", "LaTeX / Word templates", "Reference management", "Plagiarism and similarity checks", "Data analysis and plotting"],
    faqs: [
      { q: "Do you guarantee publication?", a: "No one honestly can. We strengthen the work and the writing so it stands the best chance with reviewers." },
      { q: "Is this ethical support?", a: "Yes. We guide, review and teach. The research and authorship remain yours - we do not sell authorship or fabricate results." },
      { q: "Can you help with a thesis as well?", a: "Yes, including structure, methodology chapters and defence preparation." },
    ],
  },
] as const;

export type Service = (typeof services)[number];

export function getService(slug: string) {
  return services.find((service) => service.slug === slug);
}
